#!/bin/bash
set -eu
TIMESTAMP=$(date --iso-8601=seconds)
VALUE=$(curl http://npmdeps.kemitchell.com/memory 2>/dev/null)
RSS=$(echo "$VALUE" | json rss)
TOTAL=$(echo "$VALUE" | json heapTotal)
USED=$(echo "$VALUE" | json heapUsed)
echo "$TIMESTAMP" "$RSS" "$TOTAL" "$USED"
